name: Ruby CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [2.6.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Ruby ${{ matrix.ruby-version }}
        uses: actions/setup-ruby@v1
        with:
          node-version: ${{ matrix.ruby-version }}

      - name: Run bundle install
        run: bundle install --jobs=4 --path=vendor/bundle

      - name: Run rubocop
        run: bundle exec rubocop
        env:
          CI: true

      - name: Slack Notification
        uses: homoluctus/slatify@v1.6
        if: always()
        with:
          job_name: '*Ruby CI*'
          type: ${{ job.status }}
          icon_emoji: ":octocat:"
          url: ${{ secrets.SLACK_WEBHOOK }}
